name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mattes/gce-docker-push-action@v1
      - with:
          creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          src: org/local-image:build
          dst: gcr.io/acalweb/acalwep:${{github.run_number}}-${{github.sha}}