name: Push to GCR Github Action

on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: RafikFarhad/push-to-gcr-github-action@v3
        with:
          gcloud_service_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          registry: gcr.io
          project_id: webacal
          image_name: webacal