name: Docker Build

on:
  push:
    branches:
      - main
jobs:
  buildx:
    runs-on: ubuntu-latest
      uses: mattes/gce-docker-push-action@v1
      with:
        creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        src: org/local-image:build
        dst: gcr.io/my-project/my-image:${{github.run_number}}-${{github.sha}}
